### ISSUE TITLE
Validation of homepage URI scheme

### ISSUE THREAD

**Issue by rvl** [input-output-hk/testnet-stake-pool-registry-validator#4]
When validating the `homepage` field, can we ensure that the URI scheme is either `http` or `https`?

Also there is a typo on the line with `<?> AE.Key "homepate"`.

**Comment by KtorZ** [comment]
Damn. Good point about the typo, thanks @rvl 
For the URI, it already checks about `https` and rejects non-secure URLs:

https://github.com/input-output-hk/testnet-stake-pool-registry-validator/blob/master/app/registry.hs#L400-L410

**Comment by deepfire** [comment]
@rvl, I've added a test to elaborate the https schema enforcement: https://github.com/input-output-hk/testnet-stake-pool-registry/tree/31-non-https-homepage
