### ISSUE TITLE
Error on link t.me

### ISSUE THREAD

**Issue by ruslansoluyanov** [input-output-hk/testnet-stake-pool-registry-validator#8]
https://buildkite.com/input-output-hk/production-stakepool-registry/builds/366
https://github.com/ruslansoluyanov/incentivized-testnet-stakepool-registry/blob/master/registry/ed25519_pk1vslrfvg9zes6gmx3hllmxx5wwyutes704ctdkcl4q4fxjc2qmmmqv0qtcf.json

In the configuration file, I specified a link to the chat in the telegram, I think this is not an error, but the validator rejected.

**Comment by KtorZ** [comment]
Indeed! This should be fixed now
